FeaturePack:
    Wands:
        Enabled: true
        # In game item Gold Boots, works via right click
        Lightning: 317
        # In game item Clock
        Vote: 347
        # In game item Gold Boots, works via left click
        Fireball: 317
    IPv6:
        Enabled: false
        # Permissions below is only for those who use "Permissions" those who use "GroupManager" edit group "IPv6"
        Permissions:
            - example.permission
    # This allows players to optionally secure there accounts using a password in-game.
    Secure: true
    # Don't enable unless theres a real problem.
    Debug: false
    # This hides those is server overloaded messages.
    Overloaded: true
    # This notifies players when they enter a new biome.
    BiomeMessages: false
    # This allows players with permissions to regen the world via /fp regen on off.
    Regen: true
    # This allows users to have the own time via /fp mytime day, night, dawn, dusk
    MyTime:
        Enabled: true
        # Costs 5 coins or dollars based on you're servers setup to use MyTime.
        # Do not use things like 0.5. At this moment that doesn't work.
        Cost: 5
    TimeLocking:
        # This is how long should time go on till it resets back to the locked value.
        Time: 5
    WeatherLocking:
        Time: 5
    Lottery:
        Enabled: true
        Start: 100
        Cost: 2
    God:
        GodOnTeleportOrJoin: true
        # Customize how long users get god for teleporting and joining. Default is 10 seconds which equals 200.
        # 20 server ticks per second. 10*20 = 200
        Time: 200
    Death:
        Enabled: true
        # When a OP of the game dies a golden apple is dropped.
        DropOnOPKill: 322
        # When a normal player dies a apple is dropped.
        DropOnKill: 260
    Teleport:
        Enabled: true
        # This is used to teleport you're players to a world when they fall into the void. Great for sky worlds.
        World: world
    Sign:
        Enabled: true
        Text: ClickMe
    Voting:
        Enabled: true
        # This gives players money when they vote. Leave as 0 to disable.
        Money: 0
        Time:
            Enabled: true
            # 1 is equal to one minute
            Time: 1
            # How many votes are required for the vote to not fail?
            Required: 2
            # 1 is equal to one minute
            Cooldown: 1
        Weather:
            Enabled: true
            Time: 1
            Required: 2
            Cooldown: 1
        Kill:
            Enabled: true
            Time: 1
            Required: 2
            Cooldown: 1
        # This allows players to start a vote for time to day by sleeping in a bed.
        BedVoting: true
    Tips:
        # Enable this to use Tips!
        Enabled: false
        # Input a world name exactly below to add tips for it or use Global.
        Global:
             # A period of 1 is equal to 1 minute
             - period: 1
               delay: 0
               # Enable this to display the tips below in a random order.
               random: true
               tips:
                   - $f[$cBroadcast$f]$a FeaturePack made by xzKinGzxBuRnzx
                   - $f[$cBroadcast$f]$a Please configure FeaturePack via config.yml
        world:
             - period: 1
               delay: 0
               random: false
               tips:
                   - $f[$cBroadcast$f]$a Do you have features?
             - period: 5
               delay: 0
               random: false
               tips: 
                   - Thanks for downloading FeaturePack!
    # Thanks for downloading and using FeaturePack. Should you need any help just post up a message at the bukkit forums.
    # http://bit.ly/lCFuYE